<a href="https://www.kaggle.com/code/barnitkhatiwada/mobile-price-classification-simplified?scriptVersionId=251397806" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/mobile-price-classification/train.csv
/kaggle/input/mobile-price-classification/test.csv


In [2]:
# Import necessary libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Load the dataset
file_path = '/kaggle/input/mobile-price-classification/test.csv'
data = pd.read_csv(file_path)

# Define price range conditions based on feature thresholds
conditions = [
    (data['ram'] < 2000) & (data['battery_power'] < 900) & (data['int_memory'] < 16),  # Low-end phones
    (data['ram'] >= 2000) & (data['ram'] < 4000) & (data['battery_power'] >= 900) & (data['battery_power'] < 1400),  # Mid-range phones
    (data['ram'] >= 3000) & (data['battery_power'] >= 1400) & (data['int_memory'] >= 32), # High-end phones
    
]

# Assign price ranges based on the conditions
price_range = [0, 1, 2]  # 0: Low, 1: Medium, 2: High
data['price_range'] = np.select(conditions, price_range, default=1)  # Default to medium if no conditions match



# Print the results
print(data)

       id  battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
0       1           1043     1          1.8         1  14       0           5   
1       2            841     1          0.5         1   4       1          61   
2       3           1807     1          2.8         0   1       0          27   
3       4           1546     0          0.5         1  18       1          25   
4       5           1434     0          1.4         0  11       1          49   
..    ...            ...   ...          ...       ...  ..     ...         ...   
995   996           1700     1          1.9         0   0       1          54   
996   997            609     0          1.8         1   0       0          13   
997   998           1185     0          1.4         0   1       1           8   
998   999           1533     1          0.5         1   0       0          50   
999  1000           1270     1          0.5         0   4       1          35   

     m_dep  mobile_wt  ... 

In [3]:
X= data.iloc[:,1:-1].values # selecting all columns except last one i.e. price_range
y= data.iloc[:,-1].values # selecting last column i.e. price_range

In [4]:
# splitting the dataset into test set and training set. Here, test set = 25%
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test= train_test_split(X,y, test_size=0.25, random_state=0);

In [5]:
# Although feature scaling  is not important for the tree like model 
# for example Decision tree model and random forest model.

from sklearn.preprocessing import StandardScaler
sc= StandardScaler();
sc.fit_transform(X_train);
sc.transform(X_test);

In [6]:
from sklearn.tree import DecisionTreeClassifier
classifier= DecisionTreeClassifier(criterion='entropy',random_state=0) #creating the decision tree classification model.
classifier.fit(X_train, y_train); # training the model based on training sets

In [7]:
print(classifier.predict([[2000,1,2,1,17,1,74,1,200,9,22,1300,1600,7000,18,12,12,1,1,1]])) #pridicting the mobile price classification

[2]


In [8]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1)) # displaying the predicted result along with the the actual test set result to compare

[[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [2 2]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [2 2]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [2 2]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [2 2]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [2 2]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [2 2]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [2 2]
 [1 1]
 [1 1]
 [1 1]

In [9]:
#evaluating the classification model

from sklearn.metrics import confusion_matrix, accuracy_score;
cm= confusion_matrix(y_test,y_pred)
print(cm);
print('Accuracy =',100*accuracy_score(y_test,y_pred),'%')

[[  6   0   0]
 [  2 229   0]
 [  0   0  13]]
Accuracy = 99.2 %
